#include <stdio.h>


void func(int n){
	static int cnt = 0;

	if(cnt % 6 == 0 && cnt != 0) printf("\n");
	cnt++;

	printf("%10d", n);
	if(n == 1){
		printf("\nNumber of hailstones generated: %d\n", cnt);
		return;	
	} 

	if(n % 2 == 0){
		return func(n/2);
	}
	else{
		return func(3*n+1);
	}
}

int main(){
	int input;
	printf("input initial number : ");
	scanf("%d", &input);

	printf("Hailstones generated by %d\n", input);
	func(input);
	return 0;
}